# Generated by Django 3.1.5 on 2021-02-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210201_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marksclass',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='marksclass',
            name='assign',
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('class_id', 'teacher')},
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='MarksClass',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='course',
        ),
    ]
