# Generated by Django 3.1.5 on 2021-02-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20210202_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='attendancetotal',
            unique_together={('student',)},
        ),
        migrations.DeleteModel(
            name='AssignTime',
        ),
        migrations.RemoveField(
            model_name='attendancetotal',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
