# Generated by Django 3.1.5 on 2021-02-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_assigntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
