# Generated by Django 3.1.5 on 2021-02-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20210202_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigntime',
            name='day',
        ),
        migrations.RemoveField(
            model_name='assigntime',
            name='period',
        ),
        migrations.AlterField(
            model_name='assign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
