# Generated by Django 3.1.5 on 2021-02-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_auto_20210202_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='ct_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
