# Generated by Django 3.1.5 on 2021-02-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_assign_ct_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='ct_id',
        ),
    ]
