# Generated by Django 3.1.5 on 2021-02-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_remove_assign_ct_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignTime',
        ),
    ]
