# Generated by Django 3.1.5 on 2021-02-04 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_delete_assigntime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='dept',
        ),
        migrations.AlterField(
            model_name='attendanceclass',
            name='status',
            field=models.IntegerField(default=0, help_text='2=holiday', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
    ]
