# Generated by Django 3.1.5 on 2021-02-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_auto_20210204_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='sem',
        ),
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.PositiveIntegerField(primary_key='True', serialize=False),
        ),
    ]
