# Generated by Django 3.1.5 on 2021-02-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_auto_20210204_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assign',
            new_name='AssignClassTeacher',
        ),
        migrations.RenameField(
            model_name='attendanceclass',
            old_name='assign',
            new_name='assign_ct',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.class', verbose_name='Class'),
        ),
    ]
