# Generated by Django 3.1.6 on 2021-02-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_auto_20210205_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignclassteacher',
            options={'verbose_name_plural': 'Class Teachers'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='USN',
            new_name='roll_no',
        ),
        migrations.AlterField(
            model_name='attendanceclass',
            name='assign_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.assignclassteacher', verbose_name='Class Teacher'),
        ),
    ]
